Shavida/urls.py
from cms.views import FlatPageView
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

__author__ = "Kom Sihon"

urlpatterns = patterns(
    '',
    url(r'^', include('movies.urls', namespace='movies')),
    url(r'^me/', include('me.urls', namespace='me')),
    url(r'^reporting/', include('reporting.urls', namespace='reporting')),
    url(r'^page/(?P<slug>[-\w]+)/$', FlatPageView.as_view(), name='flat_page'),
    url(r'^ikwen/', include('ikwen.urls', namespace='ikwen')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^admin/', include(admin.site.urls)),
)

me/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import *

from cms.views import get_base_context
from ikwen.views import account_setup
from me.views import History, authorize_adult
from me.views import choose_retail_bundle, choose_vod_bundle

urlpatterns = patterns(
    '',
    url(r'^history/$', History.as_view(), name='history'),
    url(r'^choose_retail_bundle$', choose_retail_bundle, name='choose_retail_bundle'),
    url(r'^choose_vod_bundle$', choose_vod_bundle, name='choose_vod_bundle'),
    url(r'^authorize_adult$', authorize_adult, name='authorize_adult'),
    url(r'^accountSetup/$', account_setup,
        {'template_name': 'me/account.html', 'extra_context': get_base_context}, name='account_setup'),
)

movies/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import *
from cms.views import BaseView, FlatPageView, Contact
from movies.views import stream, TestVideoBytesCounter, Home, MediaList, Checkout, MovieDetail, \
    get_media, get_recommended_for_single_category, Search, SeriesDetail, Bundles
from reporting.views import confirm_order, debit_vod_balance

__author__ = "Kom Sihon"

urlpatterns = patterns(
    '',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^category/(?P<slug>[-\w]+)/$', MediaList.as_view(), name='media_list'),
    url(r'^contact/$', Contact.as_view(), name='contact'),
    url(r'^bundles/$', Bundles.as_view(), name='bundles'),
    url(r'^checkout/$', Checkout.as_view(), name='checkout'),
    url(r'^page/(?P<slug>[-\w]+)/$', FlatPageView.as_view(), name='flat_page'),
    url(r'^movie/(?P<slug>[-\w]+)/$', MovieDetail.as_view(), name='movie_detail'),
    url(r'^getMovies$', get_media, name='get_media'),
    url(r'^get_recommended_for_single_category$', get_recommended_for_single_category, name='get_recommended_for_single_category'),
    url(r'^confirmOrder$', confirm_order, name='confirm_order'),
    url(r'^series/(?P<slug>[-\w]+)/$', SeriesDetail.as_view(), name='series_detail'),
    url(r'^search$', Search.as_view(), name='search'),
    url(r'^stream/(?P<media_type>[-\w]+)/(?P<item_id>[-\w]+)/$', stream, name='stream'),
    url(r'^debit_vod_balance$', debit_vod_balance, name='debit_vod_balance'),
    url(r'^testVideoBytesCounter/$', TestVideoBytesCounter.as_view()),
)

movies/views.py
# -*- coding: utf-8 -*-
import requests
from bson.objectid import ObjectId
from django.core.cache import cache

import json
from random import shuffle
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.utils.module_loading import import_by_path
from django.utils.translation import gettext as _

from cms.views import BaseView
from movies.models import *
from cms.models import *
from movies.utils import get_all_recommended, as_matrix, EXCLUDE_LIST_KEYS_KEY, get_recommended_for_category, \
    get_movies_series_share
from sales.models import RetailBundle, VODBundle, VODPrepayment


class CustomerView(BaseView):

    def get_context_data(self, **kwargs):
        context = super(CustomerView, self).get_context_data(**kwargs)
        member = self.request.user
        if member.is_authenticated():
            last_prepayment = member.profile.get_last_retail_prepayment()
            context['last_prepayment'] = last_prepayment
            available_quota = 0
            if last_prepayment:
                if last_prepayment.days_left > 0:
                    available_quota = last_prepayment.balance
            unit = getattr(settings, 'SALES_UNIT', SalesConfig.BROADCASTING_TIME)
            if unit == SalesConfig.BROADCASTING_TIME:
                display_available_quota = "%.2f GB" % (available_quota / 1000.0)
            else:
                display_available_quota = "%dh" % available_quota
            context['SALES_UNIT'] = unit
            context['SALES_UNIT_STR'] = _("GigaBytes") if unit == SalesConfig.DATA_VOLUME else _("Brodcasting hours")
            context['available_quota'] = available_quota
            context['display_available_quota'] = display_available_quota
        return context


class Home(CustomerView):
    template_name = 'movies/home.html'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        member = self.request.user
        recommended_items = []
        if member.is_authenticated():
            for item in get_all_recommended(member, 12):
                if isinstance(item, Movie):
                    item.type = 'movie'
                else:
                    item.type = 'series'
                    size = 0
                    episodes = SeriesEpisode.objects.filter(series=item)
                    for episode in episodes:
                        size += episode.size
                    item.size = size
                recommended_items.append(item)
            if len(recommended_items) < Movie.MIN_RECOMMENDED:
                additional = Movie.MIN_RECOMMENDED - len(recommended_items)
                additional_items = Movie.objects.all().order_by('-release')[:additional]
                recommended_items.append(additional_items)
        context['items'] = recommended_items
        context['recommended_items'] = as_matrix(recommended_items, 4)
        recent_releases = list(Movie.objects.all().order_by('-release', '-id')[:Movie.MAX_RECENT])
        shuffle(recent_releases)
        sample_media = recent_releases[0]
        context['fb_share_item'] = sample_media
        return context

    def render_to_response(self, context, **response_kwargs):
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/home.html'
        return super(Home, self).render_to_response(context, **response_kwargs)


class MediaList(CustomerView):
    template_name = 'movies/media_list.html'

    def get_context_data(self, **kwargs):
        context = super(MediaList, self).get_context_data(**kwargs)
        slug = kwargs['slug']
        category = Category.objects.get(slug=slug)
        context['current_category'] = category
        context['category_id'] = category.id
        context['category_top'] = Category.objects.get(slug='top')
        return context

    def get(self, request, *args, **kwargs):
        slug = kwargs['slug']
        category = get_object_or_404(Category, slug=slug)
        if category.is_adult and not self.request.user.is_authenticated():
            next_url = reverse("ikwen:sign_in") + '?next_url=' + reverse('movies:media_list', args=(category.slug, ))
            return HttpResponseRedirect(next_url)
        context = self.get_context_data(**kwargs)
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/movie_by_category.html'
        return render(request, self.template_name, context)

    def render_to_response(self, context, **response_kwargs):
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/movie_by_category.html'
        return super(MediaList, self).render_to_response(context, **response_kwargs)


class Bundles(CustomerView):
    template_name = 'movies/bundles.html'

    def get_context_data(self, **kwargs):
        context = super(Bundles, self).get_context_data(**kwargs)
        retail_bundles = RetailBundle.objects.all().order_by('quantity')
        vod_bundles = VODBundle.objects.all().order_by('volume')
        context['retail_bundles'] = retail_bundles
        for bundle in vod_bundles:
            bundle.volume /= 1000
        context['vod_bundles'] = vod_bundles
        return context

    def render_to_response(self, context, **response_kwargs):
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/bundles.html'
        return super(Bundles, self).render_to_response(context, **response_kwargs)


class MovieDetail(CustomerView):
    MAX_SUGGESTIONS = 8
    template_name = 'movies/movie_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(MovieDetail, self).get_context_data(**kwargs)
        slug = self.kwargs.get('slug', None)
        movie = get_object_or_404(Movie, slug=slug)
        context['media'] = movie
        groups = ' '.join([val.strip() for val in movie.groups.split(' ') if val != ''])
        suggestions = []
        if groups:
            suggestions = [movie for movie in
                           Movie.objects.raw_query(
                               {'$text': {'$search': groups}, 'visible': True}
                           ).exclude(pk=movie.id).order_by("-id")]
        if len(suggestions) < MovieDetail.MAX_SUGGESTIONS:
            limit = MovieDetail.MAX_SUGGESTIONS - len(suggestions)
            categories_ids = [ObjectId(category.id) for category in movie.categories]
            exclude_ids = [item.id for item in suggestions]
            exclude_ids.append(movie.id)
            categories_suggestions = [movie for movie in
                                      Movie.objects.raw_query(
                                          {'categories': {'$elemMatch': {'id': {'$in': categories_ids}}}, 'visible': True}
                                      ).exclude(pk__in=exclude_ids).order_by("-id")[:limit]]
            suggestions.extend(categories_suggestions)
        context['suggestions'] = [movie.to_dict() for movie in suggestions]
        return context

    def render_to_response(self, context, **response_kwargs):
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/movie_detail.html'
        return super(MovieDetail, self).render_to_response(context, **response_kwargs)


class SeriesDetail(CustomerView):
    MAX_SUGGESTIONS = 5
    template_name = 'movies/series_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(SeriesDetail, self).get_context_data(**kwargs)
        slug = self.kwargs.get('slug')
        current_series = get_object_or_404(Series, slug=slug)
        context['episodes'] = [ep for ep in SeriesEpisode.objects.filter(series=current_series).order_by('id')]
        context['media'] = current_series
        groups = ' '.join([val.strip() for val in current_series.groups.split(' ') if val != ''])
        suggestions = []
        if groups:
            suggestions = [series for series in
                           Series.objects.raw_query(
                               {'$text': {'$search': groups}, 'visible': True}
                           ).exclude(pk=current_series.id).order_by("-id")]
            print suggestions
        if len(suggestions) < SeriesDetail.MAX_SUGGESTIONS:
            limit = SeriesDetail.MAX_SUGGESTIONS - len(suggestions)
            categories_ids = [ObjectId(category.id) for category in current_series.categories]
            exclude_ids = [item.id for item in suggestions]
            exclude_ids.append(current_series.id)
            categories_suggestions = [series for series in
                                      Series.objects.raw_query(
                                          {'categories': {'$elemMatch': {'id': {'$in': categories_ids}}}, 'visible': True}
                                      ).exclude(pk__in=exclude_ids).order_by("-id")[:limit]]
            suggestions.extend(categories_suggestions)
        context['suggestions'] = [series.to_dict() for series in suggestions]
        return context

    def render_to_response(self, context, **response_kwargs):
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/series_detail.html'
        return super(SeriesDetail, self).render_to_response(context, **response_kwargs)


class Search(CustomerView):
    template_name = 'movies/search.html'

    def get_context_data(self, **kwargs):
        context = super(Search, self).get_context_data(**kwargs)
        context['page_title'] = ''
        radix = self.request.GET.get('q')
        items = [item.to_dict() for item in self.grab_items_by_radix(radix)]
        context['items'] = items
        return context

    def render_to_response(self, context, **response_kwargs):
        if self.request.GET.get('format') == 'json':

movies/templates/movies/bundles.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}
{% load staticfiles %}
{% block meta %}
<meta name="abstract" content="{{ WEBSITE_NAME }} - {% trans "Bundles" %}"/>
{% endblock %}
{% block page_title %} <title>{{ WEBSITE_NAME }} - {% trans "Bundles" %}</title> {% endblock %}
{% block content %}
    {% include 'snippets/fb_sdk.html' %}
    <div id="content">
        <div class="wrapper">
            <div id="bundles">
                {% for bundle in vod_bundles %}
                    <div class="bundle">
                        <h3>{{ bundle.volume }} GB</h3>
                        <div class="about text-has-shade" style="background: url('{{ bundle.movie.poster.small_url }}')">
                            <ul>
                                <li>{{ bundle.comment }}</li>
                                <li>{% blocktrans %}Valid {{ bundle.duration }} days{% endblocktrans %}</li>
                            </ul>
                            <span class="cost">{{ bundle.cost|intcomma }} {{ CURRENCY }}</span>
                            <button class="confirm order" data-id="{{ bundle.id }}" data-volume="{{ bundle.volume }}">{% trans "Choose" %}</button>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="clear"></div>
        </div>
    </div>
{% endblock %}
{% block sub_dialogs %}
    <div class="dialog confirm-bundle has-shade" style="height: 300px; width: 450px">
        <div class="stage" style="padding-top: 10px">
            <div style="font-size: 16px; text-align: left">{% trans "Confirm choice ?" %}</div>
            <div class="pay-now" style="margin-top: 15px; padding-bottom: 24px">
                <h3>{% trans "Pay now" %}</h3>
                <ul style="margin-top: 15px">
                    <li style="margin-left: 18px">
                        <img src="{% static 'img/MTN-Mobile-Money.jpg' %}" height="100"/>
                    </li>
                    <li>
                        <img src="{% static 'img/payment-logo.jpg' %}" height="100"/>
                    </li>
                </ul>
                <div class="clear"></div>
            </div>
            <p class="notice" style="background: #fff; font-size: 15px; margin: -18px auto 0; padding: 9px; width: 24px">{% trans "OR" %}</p>
            <button class="confirm" style="clear: both; margin:  10px 0">{% trans "Pay cash on a point of sale" %}</button>
        </div>
    </div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
        (function() {
            var clearCart = false;
            $('button.order').click(function() {
                $('div#lightbox .dialog').hide();
                $('div#lightbox .dialog.confirm-bundle').show();
                $('#lightbox').fadeIn();
                var bundleId = $(this).data('id'),
                    volume = parseInt($(this).data('volume')) * 1000,
                    href = "{% url 'me:choose_vod_bundle' %}?bundle_id=" + bundleId,
                    usedQuota = ikwen.getUsedQuota();
                if (usedQuota > volume) {
                    clearCart = true;
                    $('.dialog.confirm-bundle .warning.failure').show()
                } else {
                    clearCart = false;
                    $('.dialog.confirm-bundle .warning.failure').hide()
                }
                $('.dialog.confirm-bundle button.confirm').data('href', href)
            });
            $('.dialog.confirm-bundle button.confirm').click(function() {
                $(this).removeClass('confirm').addClass('disabled');
                if (clearCart) ikwen.clearCart();
                window.location = $(this).data('href');
            });
            $('.button.default').click(function() {
                $('div#lightbox .dialog').hide();
                $('#lightbox').fadeOut()
            });
            $('#side-nav').remove()
        })()
    </script>
    {% include 'snippets/google_analytics.html' %}
{% endblock %}

movies/templates/movies/checkout.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block page_title %}<title> {{ WEBSITE_NAME }} | {% trans "Summary" %} </title>{% endblock %}
{% block custom_head %}
    <style type="text/css">
        #content .wrapper section#selection, #content .wrapper section#about-pos {float: left; margin-top: 15px;padding: 0; width: 710px}
        section > .cost {float: right; font-size: 16px}
        section.subtle-shade header {border-bottom: solid 1px #F5C8B8}
        #cart {float: left; margin-top: 5px}
        #cart .panel {border: none; padding: 0; position: static; width: 720px}
        #cart .panel .movies {width: 708px}
        #cart .panel .item:nth-child(5n) {margin-right: 9px} /* This cancels the rule defined in base.css */
        #cart .panel .item:nth-child(8n) {margin-right: 0}
        #cart .cancel-delete {margin: -30px 0 0 256px;}
        #cart .panel .controls {height: 54px}
        nav#sub, #sales-logout {display: none}
    </style>
{% endblock %}
{% block content %}
    <div id="content">
        <div class="wrapper">
            <section class="subtle-shade">
                <header> {% trans "Summary" %} </header>
                <section id="selection">
                    <div class="stage" style="float: left">
                        <div class="title" style="font-size: 18px">{% trans "Your selection" %}</div>
                        <div class="spinner"></div>
                    </div>
                </section>
                <div id="summary" style="float: right; margin-top: 30px; width: 230px">
                    <div class="button confirm" style="clear: both; float: right; margin-top: 15px; padding: 10px 15px 5px">
                        <span class="icon" style="background-position:-24px -24px; margin: -6px 5px 0 0"></span>
                        <span>{% trans "Confirm checkout" %}</span>
                    </div>
                </div>
                <div class="clear"></div>
            </section>
            <div class="clear"></div>
        </div>
    </div>
{% endblock %}
{% block sub_dialogs %}
    <div class="dialog confirm has-shade">
        <div class="stage" style="height: 80px; padding: 10px 10px 6px">
            <div style="font-size: 16px">
                {% trans "Confirm checkout" %} ?
            </div>
            <div class="notice" style="clear: both; float: left; margin:  10px 0">
                En confirmant, vous vous engagez à payer au point de retrait.
            </div>
            <div class='controls' style="border-top: solid 1px #FCE5DD; clear: both; margin-top: 15px; padding-top: 5px">
                <button class="default">{% trans "Cancel" %}</button>
                <button class="confirm submit" style="margin-right: 15px">{% trans "Confirm" %}</button>
            </div>
        </div>
    </div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
        (function() {
            //Copy and Paste cart content to the #selection element !!!
            ikwen.limitCartItems = false;
            var $cart = $('#cart');
            $cart.find('.panel').removeClass('has-shade');
            ikwen.populateCartPanel();
            $cart.find('.delivery, .empty, .items-count, .controls .cost, .panel .close').remove();
            $('section#selection .spinner').remove();
            $cart.appendTo('#selection .stage').find('.panel').fadeIn();

            $('div#summary .confirm').click(function() {
                if ($(this).hasClass('disabled')) return;
                $('div#lightbox .dialog').hide();
                $('div#lightbox .dialog.confirm').show();
                $('#lightbox').fadeIn();
                $(window).css('cursor', 'wait')

            });
            $('div#lightbox .submit').click(function() {
                if ($(this).hasClass('disabled')) return;
                var endPoint = "{% url 'reporting:confirm_order' %}";
                var items = ikwen.listMovieForSave();
                ikwen.submitOrderInfo(endPoint, items, function(order) {
                    $('.top-notice-ctnr span').removeClass('failure').html(order.message);
                    $('.top-notice-ctnr').fadeIn('slow');
                });
                $('#lightbox').fadeOut()
            });

            $(window).scroll(function() {
                var bnrH = $('#cart').find('.panel .movies').height(),
                    scrollTop = $(this).scrollTop();
                if (scrollTop > 40 ) {
                    $('div#summary').hide().insertAfter('section#selection').fadeIn()
                }else if (scrollTop < 40 ){
                    $('div#summary').hide().insertAfter('section.subtle-shade header').fadeIn()
                }

            });
            $('div#lightbox button.default, div#lightbox .button.default').click(function() {
                $('div#lightbox .dialog').hide();
                $('#lightbox').fadeOut()
            })
        })()
    </script>
{% endblock %}

movies/templates/movies/home.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block meta %}
<meta name="abstract" content="{{ WEBSITE_NAME }} - {{ WEBSITE_SLOGAN }}"/>
{% endblock %}
{% block page_title %} <title>{{ WEBSITE_NAME }} - {% trans "Home" %}</title> {% endblock %}
{% block custom_head %}
    <meta property="og:image" content="{{ fb_share_item.poster.url }}"/>
    <style>
        #top nav.menu,  ul#auth {margin-top: 6px}
        #top nav.categories {display: block}
        .main.item .button {margin-top: -3px}
    </style>
{% endblock %}
{% block content %}
    {% include 'snippets/fb_sdk.html' %}
    <div id="content" class="media-list">
        <div class="wrapper" style="padding-bottom: 45px">
            {% if request.user.is_authenticated and recommended_items|length > 0 %}
                <section class="subtle-shade">
                    <header>{% trans "Recommended for you" %}</header>
                    <table class="items">
                        {% for row in recommended_items %}
                            <tr>
                                {% for item in row  %}
                                    <td>
                                        <div class='item media'>
                                            {% if item.type == 'movie' %}
                                                <a href='{% url 'movies:movie_detail' item.slug %}' target="_blank" class='poster detail inner-shade' style='background-image: url("{{ item.poster.small_url}}");'></a>
                                            {% else %}
                                                <a href="{% url 'movies:series_detail'  item.slug  %}" target="_blank" class='poster detail inner-shade' style='background-image: url("{{ item.poster.small_url}}");'></a>
                                            {% endif %}
                                            <div class='title has-faded-edge'>{{ item.title }}</div>
                                            {% include 'movies/snippets/default_media_actions.html' %}
                                        </div>
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                    <div class="clear"></div>
            </section>
            {% endif %}
            <section class="tpl" data-order_of_appearance="">
                <header><span></span>
                <a>{% trans "Show all" %}</a>
                </header>
                <table class="items">
                    <td class="tpl">
                        <div class='item media'>
                            {% include 'movies/snippets/tpl_media_actions.html' %}
                        </div>
                    </td>
                </table>
                <div class="spinner"></div>
            </section>
            <div class="clear"></div>
        </div>
    </div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript">
        (function() {
            $('tr td div.four-img').live('mouseenter' ,function() {
                $(this).addClass('hover')
            }).live('mouseleave', function() {
                $(this).removeClass('hover')
            });
            {% if request.GET.accountCreated %}
                $('.top-notice-ctnr span').html("Votre compte a été créé avec succès, vous pouvez <a href='{% url 'movies:bundles' %}'>prendre un abonnement</a> moins cher maintenant ou faire votre sélection directement</b>");
                $('.top-notice-ctnr').fadeIn('slow').delay(7000).fadeOut();
            {% endif %}
            $('div#lightbox .dialog.confirm-adult button.confirm').click(function() {
                $('body, button').css('cursor', 'wait');
                $.getJSON("{% url 'me:authorize_adult' %}", null, function(data) {
                    $('body, button').css('cursor', 'default');
                    if (data.error) alert(data.error);
                    else {
                        {% if latest_prepayment and latest_prepayment.amount >= 2500 and latest_prepayment_days_left >= 0 and count_orders_since_latest_prepayment < 4 %}
                            window.location = "{% url 'movies:home' %}#adult_autorized";
                        {% else %}
                            window.location = "{% url 'movies:bundles' %}";
                        {% endif %}
                    }
                })
            });
            function applySectionTemplate($tpl, category) {
                $tpl.attr('data-order_of_appearance', category.id);
                $tpl.find('header a').attr('href', "/category/" + category.slug);
                return $tpl
            }
            var movieCategories = [];
            {% for category in all_categories %}
                var category = {
                    id : "{{category.id}}",
                    title : "{{ category.title }}",
                    slug : "{{ category.slug }}",
                    previewsTitle : "{{ category.previews_title | safe }}"
                };
                movieCategories.push(category);
            {% endfor %}

            ikwen.mediaEndpoint = "{% url 'movies:get_recommended_for_single_category' %}";
            {% if not request.user.is_authenticated %}
                ikwen.mediaEndpoint = "{% url 'movies:get_media' %}";
            {% endif %}
            ikwen.listItemsForHome(ikwen.mediaEndpoint, movieCategories[0], applySectionTemplate);
            movieCategories.splice(0,1);
            ikwen.listItemsForHome(ikwen.mediaEndpoint, movieCategories[0], applySectionTemplate);
            movieCategories.splice(0,1);
            $(window).scroll(function() {
                var scrollTop = $(this).scrollTop();
                if ($(document).height() - $(this).height() - scrollTop <= $('footer').height()) {
                    if (movieCategories.length == 0) return;
	                ikwen.listItemsForHome(ikwen.mediaEndpoint, movieCategories[0], applySectionTemplate);
                    movieCategories.splice(0,1)
                }
            });
            function shuffle(array) {
                var counter = array.length, temp, index;
                while (counter--) {index = (Math.random() * counter) | 0;
                    temp = array[counter];
                    array[counter] = array[index];
                    array[index] = temp;
                }
                return array;
            }
            var td1 = $('<td col="1"></td>'),
                td2 = $('<td col="2"></td>'),
                td3 = $("<td colspan='2' rowspan='2' col='3'></td>");
            var topPos = [];
                td1.append($('table.top.items tr:first-child td[col=1]').html());
                td2.append($('table.top.items tr:first-child td[col=2]').html());
                td3.append($('table.top.items tr:first-child td[col=3]').html());

            topPos.push(td1);
            topPos.push(td2);
            topPos.push(td3);
            shuffle(topPos);
            $('table.top.items tr:first-child td').remove();
            for (var i=0; i<=2; i++) {
                $('table.top.items tr:first-child').append(topPos[i])
            }
            $("div#side-nav nav.smart-categories ul").find('li.recommanded').addClass('current')
        })()
    </script>
   {% include 'snippets/google_analytics.html' %}
{% endblock %}

movies/templates/movies/movie_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block meta %}<meta name="abstract" content="{{ media.title }} - {{ WEBSITE_NAME }}"/>{% endblock %}
{% block page_title %} <title>{{ media.title }} - {{ WEBSITE_NAME }}</title> {% endblock %}
{% block custom_head %}
    <meta property="og:image" content="{{ media.poster.url }}"/>
{% endblock %}
{% block content %}
    {% include 'snippets/fb_sdk.html' %}
    <div id="content" class="movie-detail">
        <div class="wrapper">
            <section>
                <header>
                    <span>{{ media.title }}</span>
                </header>
                <div id='media'>
                    <div style="margin-top: 15px">
                        <div class='item media'>
                            {% include 'movies/snippets/media_detail_actions.html' %}
                        </div>
                        <div class="categories">
                            <strong style="float: left; margin-right: 6px"> {% trans "Genre" %}: </strong>
                            <span>{{ media.categories_to_string }}</span>
                        </div>
                        <div class="synopsis">
                            <h3 class="title"> {% trans "Synopsis" %}: </h3>
                            <div class="content"> {{ media.synopsis|safe }} </div>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </section>
            <section id="suggestions">
                <header class="title" style="font-size: 18px; padding-bottom: 2px">{% trans "Suggestions" %} </header>
                <div>
                 {% for media in suggestions %}
                    <div class="item media">
                        {% include 'movies/snippets/media_detail_actions.html' %}
                    </div>
                 {% endfor %}
                </div>
            </section>
            <div class="clear"></div>
        </div>
    </div>
{% endblock %}
{% block custom_js %}
    {% if IS_VOD_OPERATOR %}
    <script type="text/javascript">
        (function() {
            $('div#top .logo > a').text("{{ media.categories.0.title }}");
        })()
    </script>
    {% endif %}
    {% include 'snippets/google_analytics.html' %}
{% endblock %}