Shavida/urls.py
from cms.views import FlatPageView
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

__author__ = "Kom Sihon"

urlpatterns = patterns(
    '',
    url(r'^', include('movies.urls', namespace='movies')),
    url(r'^me/', include('me.urls', namespace='me')),
    url(r'^reporting/', include('reporting.urls', namespace='reporting')),
    url(r'^page/(?P<slug>[-\w]+)/$', FlatPageView.as_view(), name='flat_page'),
    url(r'^ikwen/', include('ikwen.urls', namespace='ikwen')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^admin/', include(admin.site.urls)),
)

cms/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import *
from cms.views import BaseView, FlatPageView, Contact
from movies.views import stream, TestVideoBytesCounter, debit_vod_balance, Home, MediaList, Checkout, MovieDetail, \
    get_media, get_recommended_for_single_category, Search, SeriesDetail, Bundles
from reporting.views import confirm_order

_extra_context = BaseView().get_context_data()

urlpatterns = patterns('',
                       url(r'^$', Home.as_view(), name='home'),
                       url(r'^category/(?P<slug>[-\w]+)/$', MediaList.as_view(), name='media_list'),
                       url(r'^contact/$', Contact.as_view(), name='contact'),
                       url(r'^bundles/$', Bundles.as_view(), name='bundles'),
                       url(r'^checkout/$', Checkout.as_view(), name='checkout'),
                       url(r'^movie/(?P<slug>[-\w]+)/$', MovieDetail.as_view(), name='movie_detail'),
                       url(r'^getMovies$', get_media, name='get_movies'),
                       url(r'^get_recommended_for_single_category$', get_recommended_for_single_category, name='get_recommended_for_single_category'),
                       url(r'^confirmOrder$', confirm_order, name='confirm_order'),
                       url(r'^series/(?P<slug>[-\w]+)/$', SeriesDetail.as_view(), name='series_detail'),
                       url(r'^search$', Search.as_view(), name='search'),
                       url(r'^stream/(?P<item_type>[-\w]+)/(?P<item_id>[-\w]+)/$', stream, name='stream'),
                       url(r'^debit_vod_balance$', debit_vod_balance, name='debit_vod_balance'),
                       url(r'^testVideoBytesCounter/$', TestVideoBytesCounter.as_view()),
                       )

me/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import *

from cms.views import get_base_context
from ikwen.views import account_setup
from me.views import History, authorize_adult
from me.views import choose_retail_bundle, choose_vod_bundle

urlpatterns = patterns(
    '',
    url(r'^history/$', History.as_view(), name='history'),
    url(r'^choose_retail_bundle$', choose_retail_bundle, name='choose_retail_bundle'),
    url(r'^choose_vod_bundle$', choose_vod_bundle, name='choose_vod_bundle'),
    url(r'^authorize_adult$', authorize_adult, name='authorize_adult'),
    url(r'^accountSetup/$', account_setup,
        {'template_name': 'me/account.html', 'extra_context': get_base_context}, name='account_setup'),
)

reporting/urls.py
# -*- coding: utf-8 -*-

__author__ = 'Kom Sihon'

from django.conf.urls import *
from reporting.views import ContentPublicationReport, get_repo_setup_files, get_repo_files_update, confirm_order, \
    debit_vod_balance, cancel_order

urlpatterns = patterns(
    '',
    url(r'^contentPublication/$', ContentPublicationReport.as_view(), name='content_publication'),
    url(r'^get_repo_setup_files$', get_repo_setup_files, name='get_repo_setup_files'),
    url(r'^get_repo_files_update$', get_repo_files_update, name='get_repo_files_update'),
    url(r'^confirm_order$', confirm_order, name='confirm_order'),
    url(r'^debit_vod_balance$', debit_vod_balance, name='debit_vod_balance'),
    url(r'^cancel_order$', cancel_order, name='cancel_order'),
)

me/models.py
# -*- coding: utf-8 -*-
from datetime import timedelta

from Shavida.utils import is_content_vendor
from django.conf import settings
from django.db import models
from django.utils import timezone
from ikwen.models import Member
from ikwen.utils import to_dict
from django.utils.translation import gettext as _
from sales.models import SalesConfig, RetailPrepayment, VODPrepayment, Plan, ContentUpdate

DEFAULT_SITE_IMAGE = 'plan/default_site_img.jpg'


class Profile(models.Model):
    """
    Member profile
    """
    member = models.OneToOneField(Member)
    # User must activate this from his profile to access adult content
    adult_authorized = models.BooleanField(default=False, editable=False)

    is_vod_operator = models.BooleanField(default=False, editable=is_content_vendor,
                                          help_text=_("Check if this customer is a VOD Operator."))
    # The home folder of cloud installation of this member copy of the application
    home_folder = models.CharField(max_length=60, editable=False)
    # share = models.IntegerField(editable=is_content_vendor, blank=True, null=True,
    #                             help_text=_("Percentage you collect from this operator on turnover."))
    # plan = models.ForeignKey(Plan, editable=is_content_vendor, blank=True, null=True,
    #                          help_text=_("Plan of this VOD Operator."))
    created_on = models.DateTimeField(default=timezone.now)
    updated_on = models.DateTimeField(default=timezone.now, auto_now_add=True)

    def _get_days_passed_since_latest_order(self):
        orders = ContentUpdate.objects.filter(member=self.member).order_by('-id')
        latest_order = orders[0] if len(orders) > 0 else None
        now = timezone.now()
        passed_days = None
        if latest_order:
            passed_days = now - latest_order.when
        if passed_days is not None:
            return passed_days.days
        else:
            return None
    days_passed_since_latest_order = property(_get_days_passed_since_latest_order)

    _get_days_passed_since_latest_order.admin_order_field = 'days_passed_since_latest_order'
    _get_days_passed_since_latest_order.short_description = 'Days without order'

    def ordered_recently(self):
        sales_config = SalesConfig.objects.all()[0]
        if self.days_passed_since_latest_order is not None:
            if self.days_passed_since_latest_order <= sales_config.max_inactivity:
                return True
        return False
    ordered_recently.admin_order_field = 'ordered_recently'
    ordered_recently.boolean = True
    ordered_recently.short_description = 'Ordered recently?'

    def get_last_retail_prepayment(self):
        prepayments = RetailPrepayment.objects.filter(member=self.member).order_by('-id')
        return prepayments[0] if len(prepayments) > 0 else None

    def get_last_vod_prepayment(self, status=None):
        if status:
            vod_prepayments = VODPrepayment.objects.filter(member=self.member, status=status).order_by('-id')
        else:
            vod_prepayments = VODPrepayment.objects.filter(member=self.member).order_by('-id')
        return vod_prepayments[0] if len(vod_prepayments) > 0 else None

    def get_has_pending_update(self):
        return ContentUpdate.objects.filter(status=ContentUpdate.PENDING, member=self.member).count()

    def get_last_update(self):
        from sales.models import ContentUpdate
        updates = ContentUpdate.objects.filter(member=self.member).order_by('-id')
        return updates[0] if len(updates) > 0 else None

    def get_can_access_adult_content(self):
        if not self.is_vod_operator:
            last_vod_prepayment = self.get_last_vod_prepayment(VODPrepayment.CONFIRMED)
            return self.adult_authorized and last_vod_prepayment.adult_authorized
        return True

    def to_dict(self):
        can_access_adult_content = self.get_can_access_adult_content()
        var = to_dict(self)
        var['can_access_adult_content'] = can_access_adult_content
        del(var['member'])
        return var

me/forms.py
# -*- coding: utf-8 -*-

__author__ = 'Mbogning Rodrigue'

from django import forms
#from captcha.fields import ReCaptchaField


class MemberForm(forms.Form):
    phone = forms.CharField(max_length=18)
    email = forms.EmailField()
    password = forms.CharField(max_length=30)
    password1 = forms.CharField(max_length=30)


class DomainRegistrationForm(forms.Form):
    customer_name = forms.CharField(max_length=100)
    domain_type = forms.CharField(max_length=25)
    company = forms.CharField(max_length=100)
    domain_name = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=18)
    storage = forms.CharField(max_length=18)
    email = forms.EmailField()


class PasswordResetForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    #captcha = ReCaptchaField()

me/views.py
# -*- coding: utf-8 -*-

import json
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from cms.views import BaseView
from django.http.response import HttpResponseForbidden

from me.models import Profile
from sales.models import VODBundle, SalesConfig, VODPrepayment, Prepayment,\
    RetailPrepayment, RetailBundle


def offer_welcome_bundle(request, *args, **kwargs):
    sales_config = SalesConfig.objects.all()[0]
    if sales_config.free_trial:
        bytes_balance = sales_config.welcome_offer * 1000000
        VODPrepayment.objects.create(member=request.user, balance=bytes_balance, amount=0,
                                     duration=sales_config.welcome_offer_duration, status=Prepayment.CONFIRMED)


@login_required
def set_additional_session_info(request, *args, **kwargs):
    request.user.can_access_adult_content = request.user.profile.get_can_access_adult_content()
    request.user.has_pending_update = request.user.profile.get_has_pending_update()


@login_required
def create_member_profile(request, *args, **kwargs):
    member = request.user
    try:
        Profile.objects.get(member=member)
    except Profile.DoesNotExist:
        Profile.objects.create(member=member)


class History(BaseView):
    template_name = 'me/history.html'
    # TODO: Correct the display of history client side


@login_required
def choose_vod_bundle(request, *args, **kwargs):
    member = request.user
    bundle_id = request.GET.get('bundle_id')
    bundle = VODBundle.objects.get(pk=bundle_id)
    status = request.GET.get('status', Prepayment.PENDING)
    if status == Prepayment.CONFIRMED:
        # TODO: Add some logic here to verify that this bundle was actually paid
        pass
    last_vod_prepayment = member.profile.get_last_vod_prepayment()
    if last_vod_prepayment:
        try:
            welcome_offer = VODPrepayment.objects.get(member=member, paid_on__isnull=True, status=Prepayment.CONFIRMED)
            if last_vod_prepayment.status == Prepayment.PENDING and last_vod_prepayment != welcome_offer:
                last_vod_prepayment.delete()  # This VODPrepayment was never paid so wipe it out
                balance = bundle.volume + welcome_offer.balance
            else:
                balance = last_vod_prepayment.balance + bundle.volume
        except VODPrepayment.DoesNotExist:
            if last_vod_prepayment.status == Prepayment.PENDING:
                balance= 0
                last_vod_prepayment.delete()  # This VODPrepayment was never paid so wipe it out
            else:
                balance = last_vod_prepayment.balance + bundle.volume
    else:
        balance = bundle.volume
    VODPrepayment.objects.create(member=member, amount=bundle.cost, duration=bundle.duration,
                                 balance=balance, adult_authorized=bundle.adult_authorized, status=status)
    return HttpResponseRedirect(reverse('me:account_setup') + "?bundleChosen=yes")


@login_required
def choose_retail_bundle(request, *args, **kwargs):
    member = request.user
    if not member.profile.is_vod_operator:
        return HttpResponseForbidden("You are not allowed to order retail bundle.")
    bundle_id = request.GET.get('bundle_id')
    bundle = RetailBundle.objects.get(pk=bundle_id)
    status = request.GET.get('status', Prepayment.PENDING)
    if status == Prepayment.CONFIRMED:
        # TODO: Add some logic here to verify that this bundle was actually paid
        pass
    last_retail_prepayment = member.profile.get_last_retail_prepayment()
    if last_retail_prepayment:
        balance = last_retail_prepayment.balance + bundle.volume
    else:
        balance = bundle.volume
    RetailPrepayment.objects.create(member=member, amount=bundle.cost, duration=bundle.duration,
                                    balance=balance, adult_authorized=bundle.adult_authorized, status=status)
    return HttpResponseRedirect(reverse('movies:home') + "?bundleChosen=yes")


@login_required
def authorize_adult(request, *args, **kwargs):
    member = request.user
    member.profile.adult_authorized = True
    member.profile.save()
    return HttpResponse(
        json.dumps({'success': True}),
        content_type='application/json'
    )

me/templates/me/account.html
{% extends "ikwen/account.html" %}
{% load i18n %}
{% load humanize %}
{% load staticfiles %}
{% block sub_custom_head %}
    <style>
        .wrapper section.plan label {width: 240px}
        .wrapper section.plan span {float: left}
        .wrapper section .action-edit {color: #BD7300; cursor: pointer; font-size: 15px}
        .wrapper section .multi-lines {float: left; font-size: 15px}
        .update-result {position: absolute; width: 500px}
        .update-result .message {margin: -15px auto 0; width: 360px}
        .wrapper section form label {font-size: 14px; font-weight: normal; margin-right: 15px; text-align: right; width: 180px}
        .wrapper section form button {width: 78px}
        #adult-warning {border: 1px solid #fd5d5d; float: left; margin-top: 15px; padding: 6px 2%; width: 96%}
        .dialog.confirm-adult p {float: right; margin: 12px 20px 0 0; width: 400px}
        .dialog.confirm-adult button {float: right; width: 100px}
    </style>
{% endblock %}

{% block custom_info %}
    <div style="float: right; width: 480px">
        <section class="plan" style=" width: 450px">
            <div class="update-result">
                <p class="message hidden"></p>
            </div>
            <header>
                <span> {% trans "Bundle" %} </span>
                <span class="icon" style="background-position: -158px -9px"></span>
            </header>
            <div class="detail">
                {% if last_vod_prepayment %}
                    <label>{% trans "Last refill" %}</label>
                    <div class="multi-lines">
                        <div>
                            <span> <b> {{ last_vod_prepayment.amount|intcomma }} {{ CURRENCY }} </b> - {{ last_vod_prepayment.view_when }}</span>
                            {% if last_vod_prepayment.days_left < 0 %}
                                <span class="minor expired"><b>{% trans "Your bundle is sold out." %}</b></span>
                            {% else %}
                                <span class="minor"><b>{{ last_vod_prepayment.balance }} GB</b> {% trans "left" %}</span>
                            {% endif %}
                        </div>
                        <a href="{% url 'movies:bundles' %}" style="clear:both; float: left"> {% trans "Extend" %}</a>
                    </div>
                {% else %}
                    <label>{% trans "No bundle" %}</label>
                    <a href="{% url 'movies:bundles' %}" class="action-edit">{% trans "Choose a bundle" %}</a>
                {% endif %}
            </div>
            {% if last_vod_prepayment and last_vod_prepayment.days_left >= 0 %}
                <div class="detail" style="clear: both">
                    <label>{% trans "Expiry" %}</label>
                    <div class="multi-lines">
                        <div>
                            <span><b>{{ last_vod_prepayment.days_left }}</b> {% trans "day(s) left" %}</span>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% if not request.user.can_order_adult %}
                <div id="adult-warning">
                    <img src="{% static 'img/warning-icon.png' %}" width="45" style="float: left"/>
                    {% if not request.user.adult_authorized %}
                        {% blocktrans %}
                            <span style="margin: 12px 0 0 15px">You don't have access to adult content - <a href="#">Activate access</a> *</span>
                        {% endblocktrans %}
                    {% endif %}
                </div>
            {% endif %}
        </section>
    </div>
{% endblock %}
{% block lightbox_dialogs %}
    <div class="dialog confirm-adult has-shade" style="border: 1px solid #fd5d5d; width: 510px; height: 212px;">
        <div class="stage" style="height: 80px; padding: 10px 10px 6px">
            <div style="font-size: 16px">
                <img src="{% static 'img/warning-icon.png' %}" width="45" style="float: left"/>
                <span style="margin: 12px 0 0 24px">{% trans "Confirm" %}</span>
            </div>
            <p style="line-height: 24px; text-align: justify">
                {% trans "By activating this content you confirm that you meet the requirements regarding age in your country." %}
            </p>
            <p style="color: #BB7A66; font-size: 11px; margin-bottom: 10px"> * Seul un forfait d'au moins <strong>2 500 F</strong> permet d'y avoir accès.</p>
            <div class='controls' style="border-top: solid 1px #FCE5DD; clear: both; margin-top: 15px; padding-top: 5px">
                <button class="default">Annuler</button>
                <button class="confirm" style="margin-right: 15px">Confirmer</button>
            </div>
        </div>
    </div>
{% endblock %}
{% block sub_custom_js %}
    <script>
        (function() {
            $('div#adult-warning a').click(function() {
                $('#lightbox').fadeIn();
                return false
            });
            $('.dialog.confirm-adult button.confirm').click(function() {
                $('body, button').css('cursor', 'wait');
                $.getJSON("{% url 'me:authorize_adult' %}", null, function(data) {
                    $('body, button').css('cursor', 'default');
                    if (data.error) alert(data.error);
                    else {
                        $('div#adult-warning span:first').hide();
                        $('div#adult-warning span:last').show();
                        $('#lightbox').fadeOut()
                    }
                })
            });
            $('div#lightbox button.default').click(function() {
                $('div#lightbox .dialog').hide();
                $('#lightbox').fadeOut()
            });
            {% if request.GET.bundleChosen %}
                $('div#top-notice-ctnr span').html("Votre forfait a été activé avec succès, vous pouvez <a href='{% url 'movies:home' %}'><b>commander maintenant</b></a>");
                $('div#top-notice-ctnr').fadeIn('slow');
            {% endif %}
            {% if welcome_offer %}
                $('div#top-notice-ctnr span').html("Bienvenue sur Cinemax.club. Vous bénéficiez de <strong>1 Giga de films gratuit</strong> - <a href='{% url 'movies:home' %}'><b>Commandez maintenant</b></a>");
                $('div#top-notice-ctnr').fadeIn('slow');
            {% endif %}
        })()
    </script>
{% endblock %}

me/templates/me/base.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div id="content">
        <div class="wrapper">
            <nav id="sub">
                <ul>
                    <li> <a href="{% url 'me:history' %}" class="history"> {% trans "Historique" %} </a> </li>
                    <li> <a href="{% url 'ikwen:account_setup' %}" class="account"> {% trans "Infos compte" %} </a> </li>
                </ul>
            </nav>
            {% block content_stage %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

me/templates/me/history.html
{% extends "me/base.html" %}
{% load i18n %}
{% load staticfiles %}
{% block page_title %} <title>{{ WEBSITE_NAME }} - {% trans "History" %}</title> {% endblock %}
{% block custom_head %}
    <style type="text/css">
        nav#sub .history {border-bottom: 2px solid #BB4824; color: #300c00; font-weight: bold}
        #content {min-height: 450px}
        #content .order {border: solid 1px #FCE5DD; cursor: pointer; float: left; margin: 6px 10px 15px 0; height: 280px; padding: 9px; width: 210px;}
        .highlight {background: #FCE5DD}
        #content .order .poster {background: no-repeat center -8px; background-size: 230px auto;float: left; height: 230px; width: 210px}

        #content .order div {text-align: center}
        #content .order .cost span:first-child {float: left; margin:13px 8px}
        #content .order .date {color: #300C00; float: left; font-size: 16px; height: 20px; margin-top: 10px; width: 176px}
        #content .order .summary {color: #BB7A66; float: left; font-size: 13px; width: 100%}
        #content .order .summary span {float: none}
        #content .order .size {float: left; width: 100%}
        #content .order .size span {margin-right: 3px}
        #content .order .amount {margin-top: 5px}
        #content .order .currency {margin: 5px 0 0 2px}
        .row, .row .master, .row .details {float: left; width: 100%}
        .master .order-row {height: 300px}
        .row .details {border-top: 1px solid #FCE5DD; float: left; padding-bottom: 27px}
        .row .details .stage {float: left; margin-left: 5px; width: 770px}
        .stage .movie {float: left; height: 85px; margin: 5px; width: 80px}

        nav#sub, #sales-logout {display: none}
        .details .movie {background: no-repeat center -8px; background-size: 80px auto; border: 1px solid #FCE5DD; float: left; height: 80px; margin: 4px 3px 0 0; overflow: hidden; width: 80px}
        .details .movie .about {background: rgba(255, 255, 255, .85); height: 27px; top: 53px; padding-left: 3px; position: relative}
        .details .movie .about .title  {color: #7E594C}
        .details .movie .name {height: 14px; text-transform: capitalize}
    </style>
{% endblock %}
{% block content_stage %}
    <div id="content">
        <div class="wrapper">
            <section class="subtle-shade">
                <header>{% trans "Recent orders" %}</header>
                <div class="stage">
                    <div class="spinner" style="clear: both; height: 240px"></div>
                    {% if IS_VOD_OPERATOR %}
                        <div class="no-result hidden">
                            <span style="margin: 7px 20px 0 0">{% trans "You never watched anything before" %}</span>
                            <a href="{% url 'movies:home' %}" class="button default">{% trans "Try now" %}</a>
                        </div>
                    {% else %}
                        <div class="no-result hidden">
                            <span style="margin: 7px 20px 0 0">{% trans "You never ordered before" %}</span>
                            <a href="{% url 'movies:home' %}" class="button default">{% trans "Try now" %}</a>
                        </div>
                    {% endif %}
                    <div class="row">
                        <div class="master">
                            <div class='order tpl' orderId="">
                                <div class="poster"></div>
                                <div class='date'> 28/08/2014 </div>
                                <div class="summary">
                                    <span class="size"> 32 </span> Eléments -
                                    <span class='amount hidden'>2300</span>
                                    <span class="currency">Fr</span>
                                </div>
                            </div>
                        </div>
                        <div class="details hidden">
                            <div class="close caution text-has-shade" style="font-size: 18px"> X </div>
                            <div class="stage">
                                <div class='movie tpl hidden'>
                                    <div class="about">
                                        <div class='name has-faded-edge'>
                                            <span class="title"></span>
                                            <span class="faded-edge"></span>
                                        </div>
                                        <div class='cost hidden'>
                                            <span class="value"></span>
                                            <span>Fr</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% if IS_CONTENT_VENDOR %}
                                <span class="button warning" style="float: right; margin: 24px 5px 0 0">{% trans "Cancel order" %}</span>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </section>
            <div class="clear"></div>
        </div>
    </div>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="{% static 'me/js/me.js' %}"></script>
    <script type="text/javascript">
        (function() {
            var origin = 'site';
            $('.row .details .close').click(function() {
                $('.row .details').hide()
            });
            $('div#content .order').live('click', function() {
                if (!$(this).hasClass('highlight')) {
                    $('.highlight').removeClass('highlight')
                }
                var $ordersRow = $(this).parent(),
                    orderId = $(this).attr('id'),
                    status = $(this).attr('status');
                $('.details .movie').hide();
                $('.details .movie[orderId=' + orderId + ']').show();
                if (status == 'Pending' || status == 'Authorized')
                    $('.details .button.warning, a#find-pos, .dialog.point-of-sales input').attr('orderId', orderId).show();
                else $('.details .button.warning, a#find-pos').hide();
                $('.row .details').insertAfter($ordersRow).show()
            });
            $('.row .button.warning').click(function() {
                if (!confirm("Sure you want to cancel this order ?")) return;
                var orderId = $(this).attr('orderId');
                ikwen.cancelOrder("{% url 'reporting:cancel_order' %}", orderId)
            });
            {% if request.GET.cancelLast %}
                ikwen.listOrders("{% url 'me:history' %}", origin, function() {
                    $('div#content .details').addClass('highlight');
                    $('div#content .order[status=Pending], div#content .order[status=Authorized]').addClass('highlight').click()
                });
            {% else %}
			    ikwen.listOrders("{% url 'me:history' %}", origin);
            {% endif %}
        })()
    </script>
{% endblock %}