Shavida/urls.py
from cms.views import FlatPageView
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

__author__ = "Kom Sihon"

urlpatterns = patterns(
    '',
    url(r'^', include('movies.urls', namespace='movies')),
    url(r'^me/', include('me.urls', namespace='me')),
    url(r'^reporting/', include('reporting.urls', namespace='reporting')),
    url(r'^page/(?P<slug>[-\w]+)/$', FlatPageView.as_view(), name='flat_page'),
    url(r'^ikwen/', include('ikwen.urls', namespace='ikwen')),
    url(r'^i18n/', include('django.conf.urls.i18n')),

    url(r'^admin/', include(admin.site.urls)),
)

me/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import *

from cms.views import get_base_context
from ikwen.views import account_setup
from me.views import History, authorize_adult
from me.views import choose_retail_bundle, choose_vod_bundle

urlpatterns = patterns(
    '',
    url(r'^history/$', History.as_view(), name='history'),
    url(r'^choose_retail_bundle$', choose_retail_bundle, name='choose_retail_bundle'),
    url(r'^choose_vod_bundle$', choose_vod_bundle, name='choose_vod_bundle'),
    url(r'^authorize_adult$', authorize_adult, name='authorize_adult'),
    url(r'^accountSetup/$', account_setup,
        {'template_name': 'me/account.html', 'extra_context': get_base_context}, name='account_setup'),
)

movies/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import *
from cms.views import BaseView, FlatPageView, Contact
from movies.views import stream, TestVideoBytesCounter, Home, MediaList, Checkout, MovieDetail, \
    get_media, get_recommended_for_single_category, Search, SeriesDetail, Bundles
from reporting.views import confirm_order, debit_vod_balance

__author__ = "Kom Sihon"

urlpatterns = patterns(
    '',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^category/(?P<slug>[-\w]+)/$', MediaList.as_view(), name='media_list'),
    url(r'^contact/$', Contact.as_view(), name='contact'),
    url(r'^bundles/$', Bundles.as_view(), name='bundles'),
    url(r'^checkout/$', Checkout.as_view(), name='checkout'),
    url(r'^page/(?P<slug>[-\w]+)/$', FlatPageView.as_view(), name='flat_page'),
    url(r'^movie/(?P<slug>[-\w]+)/$', MovieDetail.as_view(), name='movie_detail'),
    url(r'^getMovies$', get_media, name='get_media'),
    url(r'^get_recommended_for_single_category$', get_recommended_for_single_category, name='get_recommended_for_single_category'),
    url(r'^confirmOrder$', confirm_order, name='confirm_order'),
    url(r'^series/(?P<slug>[-\w]+)/$', SeriesDetail.as_view(), name='series_detail'),
    url(r'^search$', Search.as_view(), name='search'),
    url(r'^stream/(?P<media_type>[-\w]+)/(?P<item_id>[-\w]+)/$', stream, name='stream'),
    url(r'^debit_vod_balance$', debit_vod_balance, name='debit_vod_balance'),
    url(r'^testVideoBytesCounter/$', TestVideoBytesCounter.as_view()),
)

reporting/urls.py
# -*- coding: utf-8 -*-

__author__ = 'Kom Sihon'

from django.conf.urls import *
from reporting.views import ContentPublicationReport, get_repo_setup_files, get_repo_files_update, confirm_order, \
    debit_vod_balance, cancel_order

urlpatterns = patterns(
    '',
    url(r'^contentPublication/$', ContentPublicationReport.as_view(), name='content_publication'),
    url(r'^get_repo_setup_files$', get_repo_setup_files, name='get_repo_setup_files'),
    url(r'^get_repo_files_update$', get_repo_files_update, name='get_repo_files_update'),
    url(r'^confirm_order$', confirm_order, name='confirm_order'),
    url(r'^debit_vod_balance$', debit_vod_balance, name='debit_vod_balance'),
    url(r'^cancel_order$', cancel_order, name='cancel_order'),
)

movies/views.py
# -*- coding: utf-8 -*-
import requests
from bson.objectid import ObjectId
from django.core.cache import cache

import json
from random import shuffle
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render
from django.template.defaultfilters import slugify
from django.utils.module_loading import import_by_path
from django.utils.translation import gettext as _

from cms.views import BaseView
from movies.models import *
from cms.models import *
from movies.utils import get_all_recommended, as_matrix, EXCLUDE_LIST_KEYS_KEY, get_recommended_for_category, \
    get_movies_series_share
from sales.models import RetailBundle, VODBundle, VODPrepayment


class CustomerView(BaseView):

    def get_context_data(self, **kwargs):
        context = super(CustomerView, self).get_context_data(**kwargs)
        member = self.request.user
        if member.is_authenticated():
            last_prepayment = member.profile.get_last_retail_prepayment()
            context['last_prepayment'] = last_prepayment
            available_quota = 0
            if last_prepayment:
                if last_prepayment.days_left > 0:
                    available_quota = last_prepayment.balance
            unit = getattr(settings, 'SALES_UNIT', SalesConfig.BROADCASTING_TIME)
            if unit == SalesConfig.BROADCASTING_TIME:
                display_available_quota = "%.2f GB" % (available_quota / 1000.0)
            else:
                display_available_quota = "%dh" % available_quota
            context['SALES_UNIT'] = unit
            context['SALES_UNIT_STR'] = _("GigaBytes") if unit == SalesConfig.DATA_VOLUME else _("Brodcasting hours")
            context['available_quota'] = available_quota
            context['display_available_quota'] = display_available_quota
        return context


class Home(CustomerView):
    template_name = 'movies/home.html'

    def get_context_data(self, **kwargs):
        context = super(Home, self).get_context_data(**kwargs)
        member = self.request.user
        recommended_items = []
        if member.is_authenticated():
            for item in get_all_recommended(member, 12):
                if isinstance(item, Movie):
                    item.type = 'movie'
                else:
                    item.type = 'series'
                    size = 0
                    episodes = SeriesEpisode.objects.filter(series=item)
                    for episode in episodes:
                        size += episode.size
                    item.size = size
                recommended_items.append(item)
            if len(recommended_items) < Movie.MIN_RECOMMENDED:
                additional = Movie.MIN_RECOMMENDED - len(recommended_items)
                additional_items = Movie.objects.all().order_by('-release')[:additional]
                recommended_items.append(additional_items)
        context['items'] = recommended_items
        context['recommended_items'] = as_matrix(recommended_items, 4)
        recent_releases = list(Movie.objects.all().order_by('-release', '-id')[:Movie.MAX_RECENT])
        shuffle(recent_releases)
        sample_media = recent_releases[0]
        context['fb_share_item'] = sample_media
        return context

    def render_to_response(self, context, **response_kwargs):
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/home.html'
        return super(Home, self).render_to_response(context, **response_kwargs)


class MediaList(CustomerView):
    template_name = 'movies/media_list.html'

    def get_context_data(self, **kwargs):
        context = super(MediaList, self).get_context_data(**kwargs)
        slug = kwargs['slug']
        category = Category.objects.get(slug=slug)
        context['current_category'] = category
        context['category_id'] = category.id
        context['category_top'] = Category.objects.get(slug='top')
        return context

    def get(self, request, *args, **kwargs):
        slug = kwargs['slug']
        category = get_object_or_404(Category, slug=slug)
        if category.is_adult and not self.request.user.is_authenticated():
            next_url = reverse("ikwen:sign_in") + '?next_url=' + reverse('movies:media_list', args=(category.slug, ))
            return HttpResponseRedirect(next_url)
        context = self.get_context_data(**kwargs)
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/movie_by_category.html'
        return render(request, self.template_name, context)

    def render_to_response(self, context, **response_kwargs):
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/movie_by_category.html'
        return super(MediaList, self).render_to_response(context, **response_kwargs)


class Bundles(CustomerView):
    template_name = 'movies/bundles.html'

    def get_context_data(self, **kwargs):
        context = super(Bundles, self).get_context_data(**kwargs)
        retail_bundles = RetailBundle.objects.all().order_by('quantity')
        vod_bundles = VODBundle.objects.all().order_by('volume')
        context['retail_bundles'] = retail_bundles
        for bundle in vod_bundles:
            bundle.volume /= 1000
        context['vod_bundles'] = vod_bundles
        return context

    def render_to_response(self, context, **response_kwargs):
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/bundles.html'
        return super(Bundles, self).render_to_response(context, **response_kwargs)


class MovieDetail(CustomerView):
    MAX_SUGGESTIONS = 8
    template_name = 'movies/movie_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(MovieDetail, self).get_context_data(**kwargs)
        slug = self.kwargs.get('slug', None)
        movie = get_object_or_404(Movie, slug=slug)
        context['media'] = movie
        groups = ' '.join([val.strip() for val in movie.groups.split(' ') if val != ''])
        suggestions = []
        if groups:
            suggestions = [movie for movie in
                           Movie.objects.raw_query(
                               {'$text': {'$search': groups}, 'visible': True}
                           ).exclude(pk=movie.id).order_by("-id")]
        if len(suggestions) < MovieDetail.MAX_SUGGESTIONS:
            limit = MovieDetail.MAX_SUGGESTIONS - len(suggestions)
            categories_ids = [ObjectId(category.id) for category in movie.categories]
            exclude_ids = [item.id for item in suggestions]
            exclude_ids.append(movie.id)
            categories_suggestions = [movie for movie in
                                      Movie.objects.raw_query(
                                          {'categories': {'$elemMatch': {'id': {'$in': categories_ids}}}, 'visible': True}
                                      ).exclude(pk__in=exclude_ids).order_by("-id")[:limit]]
            suggestions.extend(categories_suggestions)
        context['suggestions'] = [movie.to_dict() for movie in suggestions]
        return context

    def render_to_response(self, context, **response_kwargs):
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/movie_detail.html'
        return super(MovieDetail, self).render_to_response(context, **response_kwargs)


class SeriesDetail(CustomerView):
    MAX_SUGGESTIONS = 5
    template_name = 'movies/series_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(SeriesDetail, self).get_context_data(**kwargs)
        slug = self.kwargs.get('slug')
        current_series = get_object_or_404(Series, slug=slug)
        context['episodes'] = [ep for ep in SeriesEpisode.objects.filter(series=current_series).order_by('id')]
        context['media'] = current_series
        groups = ' '.join([val.strip() for val in current_series.groups.split(' ') if val != ''])
        suggestions = []
        if groups:
            suggestions = [series for series in
                           Series.objects.raw_query(
                               {'$text': {'$search': groups}, 'visible': True}
                           ).exclude(pk=current_series.id).order_by("-id")]
            print suggestions
        if len(suggestions) < SeriesDetail.MAX_SUGGESTIONS:
            limit = SeriesDetail.MAX_SUGGESTIONS - len(suggestions)
            categories_ids = [ObjectId(category.id) for category in current_series.categories]
            exclude_ids = [item.id for item in suggestions]
            exclude_ids.append(current_series.id)
            categories_suggestions = [series for series in
                                      Series.objects.raw_query(
                                          {'categories': {'$elemMatch': {'id': {'$in': categories_ids}}}, 'visible': True}
                                      ).exclude(pk__in=exclude_ids).order_by("-id")[:limit]]
            suggestions.extend(categories_suggestions)
        context['suggestions'] = [series.to_dict() for series in suggestions]
        return context

    def render_to_response(self, context, **response_kwargs):
        if is_touch_device(self.request):
            self.template_name = 'movies/touch/series_detail.html'
        return super(SeriesDetail, self).render_to_response(context, **response_kwargs)


class Search(CustomerView):
    template_name = 'movies/search.html'

    def get_context_data(self, **kwargs):
        context = super(Search, self).get_context_data(**kwargs)
        context['page_title'] = ''
        radix = self.request.GET.get('q')
        items = [item.to_dict() for item in self.grab_items_by_radix(radix)]
        context['items'] = items
        return context

    def render_to_response(self, context, **response_kwargs):
        if self.request.GET.get('format') == 'json':

movies/templates/movies/snippets/global_handlers.html
{% load i18n %}
<script type="text/javascript">
    (function() {
        /**********************************************************************/
        /************************   GLOBAL HANDLERS    ************************/
        /**********************************************************************/
        {% if request.user.is_authenticated %}
            ikwen.availableQuota = parseInt("{{ available_quota }}");
            ikwen.canAccessAdultContent = "{{ request.user.can_access_adult_content }}".toLowerCase();
        {% endif %}

        var itemsCount = localStorage.getItem('itemsCount');
        if (!itemsCount) itemsCount = 0;
        $('div#cart .items-count span').text(itemsCount);

        $('form#search').submit(function() {
            var q = ikwen.stripArticles($(this).find('[name=radix]').val());
            $(this).find('[name=q]').val(q)
        });
        $('form#search input').focusin(function() {
           $('form#search .icon.magnifier').hide();
           $(this).animate({width: 270}, 'normal', 'swing');
           $('#search-result').removeClass('hidden')
        }).blur(function() {
            $(this).animate({width: 216}, 'normal', 'swing', function() {$('form#search .icon.magnifier').show()});
            $(this).val("");
            $('#search-results').fadeOut()
        }).keyup(function() {
            var str = $(this).val();
            str = ikwen.stripArticles(str);
            ikwen.search("{% url 'movies:search' %}" , str, '#search-results', 'div#search-results .movie', 'form#search .spinner')
        });
        $('div#top .login').click(function() {
            $('#login-panel').slideDown()
        });
        $('div#login-panel .close').click(function() {
            $('#login-panel').slideUp()
        });
        $('#user-menu').click(function() {
            $('div#user-menu .panel').slideDown()
        });
        $('div#user-menu .panel').mouseleave(function() {
            $('div#user-menu .panel').slideUp()
        });
        $('div#user-menu .logout').click(function() {
            localStorage.removeItem('moviesSelection');
            localStorage.removeItem('seriesSelection');
            localStorage.removeItem('itemsCount')
        });
        $('div#content.media-list .item:not(.main)').live('mouseenter', function() {
            $(this).find('a.poster').animate({height:190},'swing')
        }).live('mouseleave', function(){
            $(this).find('a.poster').animate({height: 230},'swing')
        });
     // ask the user to connect if he is not when trying to order movies
        $('.media .connect').live('click', function() {
            $('div#lightbox .dialog').hide();
            $('div#lightbox .dialog.login-required').show();
            $('#lightbox').fadeIn();
            return false
        });
        $('button.processing, a.button.processing').live('click', function() {
            var notice = "{% blocktrans %}Sorry! You have a pending update - <a href='{{ history_url }}?cancelLast=yes'>Cancel it</a>{% endblocktrans %}";
            $('.top-notice-ctnr span').html(notice);
            $('.top-notice-ctnr').hide().fadeIn();
            return false
        });
        $('div#lightbox .cancel.default, div#lightbox .close').click(function() {
            $('#lightbox').fadeOut()
        });
        /********************************************************************/
        /***********************    CART HANDLERS    ************************/
        /********************************************************************/
        ikwen.limitCartItems = true;  // Cause the cart to display only some of the items. Limit is given by MAX_VISIBLE_CART_ITEMS
        $('div#cart .empty').click(function() {
            if (confirm("{% trans "Sure you want to empty the cart ?" %}")) {
                ikwen.clearCart()
            } else return false
        });
        $('button.order.confirm, a.order.confirm').live('click', function() {
            var load = $(this).data('load');
            if (!ikwen.hasEnoughBalance(load)) {
                var notice = "{% blocktrans %}Sorry, your quota has been exhausted. <b><a href='{{ bundles_url }}'>Take a new bundle</a></b>{% endblocktrans %}";
                $('.top-notice-ctnr span').html(notice).addClass('failure');
                $('.top-notice-ctnr').hide().fadeIn().delay(10000).fadeOut();
                ikwen.warnedAboutStorage = true;
                return false
            }
            var item = {
                type: $(this).data('type'),
                id: $(this).data('id'),
                price: $(this).data('price'),
                load: load,
                title: $(this).data('title'),
                poster: {
                    small_url: $(this).data('poster')
                }
            };
            if ($('div#cart .item:not(.tpl)').length == 0) $('div#cart .panel').slideDown();
            ikwen.addToCart(item);
            ikwen.populateCartPanel()
        });

        $('div#cart .items-count').click(function() {
            $('div#cart .panel').slideDown();
        });
        $('div#cart .panel .close').click(function() {
            $('div#cart .panel').slideUp()
        });
        $('div#cart .panel .item').live('mouseenter', function() {
            $(this).find('.delete-bg, .delete').show();
        }).live('mouseleave', function() {
            $(this).find('.delete-bg, .delete').hide();
        });
        $('div#cart .item .delete').live('click', function() {
            var index = $(this).parents('.item').index(),
                type = $(this).parents('.item').attr('type');
            ikwen.removeFromCart(index, type);
            $("div#cart .cancel-delete").fadeIn().delay(6000).fadeOut();
            ikwen.populateCartPanel()
        });
        $('div#lightbox .login, .no-result a.login-for-more').click(function() {
            $('#login-panel').slideDown();
            $('div#login-panel form input:first').focus();
            $('#lightbox').fadeOut();
            return false
        });
        $('div#cart .cancel-delete .action').click(function() {
            ikwen.addToCart(ikwen.latestDeletedElt.item, ikwen.latestDeletedElt.index);
            ikwen.populateCartPanel();
            $("div#cart .cancel-delete").fadeOut()
        });
        $('div#cart .no-movie .show-form').click(function() {
            $('#auto-selection').fadeIn();
            $(this).hide()
        });
        $('form#auto-selection .hide').click(function() {
            $('#auto-selection').fadeOut();
            $('div#cart .no-movie .show-form').show()
        });
        $('form#auto-selection').submit(function() {
            var moviesLoad = $('input#movies-qty').val(),
                seriesLoad = $('input#series-qty').val(),
                load = moviesLoad + seriesLoad,
                salesUnit = "{{ SALES_UNIT }}";
            if (salesUnit == "Volume") load *= 1000;
            if (!ikwen.hasEnoughBalance(load)) {
                var notice = "{% blocktrans %}Sorry, your quota is insufficient. <b><a href='{{ bundles_url }}'>Take a new bundle</a></b>{% endblocktrans %}";
                $('.top-notice-ctnr span').html(notice).addClass('failure');
                $('.top-notice-ctnr').hide().fadeIn().delay(10000).fadeOut();
                return false
            }
            ikwen.launchAutoSelection("{% url 'reporting:get_repo_setup_files' %}", moviesLoad, seriesLoad);
            return false;
        });
        $('a#find-pos').live('click', function() {
            $('div#lightbox .dialog').hide();
            $('div#lightbox .dialog.point-of-sales').show();
            $('#lightbox').fadeIn();
            $('div#lightbox .dialog.point-of-sales input').focus();
            return false
        });

        $('div.estimation a').click(function() {
            $('div#lightbox .dialog').hide();
            $('div#lightbox .dialog.point-of-sales').show();
            $('#lightbox').fadeIn();
            $('div#lightbox .dialog.point-of-sales input').focus();
            //$(this).first().hide();
            $('div.estimation a:first-child').hide();
            $('div.estimation .time').fadeIn();
            return false
        });
        if (localStorage.getItem('downloadSpeed')) {
            $('div.estimation a:first-child').hide();
            $('div.estimation .time').fadeIn();
        }
        $(window).bind('storage', ikwen.populateCartPanel);
        ikwen.populateCartPanel();

        /********************************************************************/
        /***********************    FREEZE TOP BAR HANDLERS    **************/
        /********************************************************************/

        $(window).scroll(function() {
            var topH = 41,
                scrollTop = $(this).scrollTop();
            if (scrollTop > topH) {
                if (!$('div#top').hasClass('frozen'))
                    $('#top').addClass('frozen has-shade').hide().fadeIn();
                    $('#side-nav').css('margin-top', '40px')
            }
            if (scrollTop < topH) {
                $('#top').removeClass('frozen has-shade');
                $('#side-nav').css('margin-top', '28px')
            }
        });
        var $sideNav = $('#side-nav'),
            $more = $('#more-categories');

        $('div#top > div:first-child').mouseenter(function() {
            if($sideNav.hasClass('visible')) return false;
            $sideNav.addClass('visible').animate({marginLeft: 0});
                $('#side-nav').find('nav li.more').mouseenter(function() {
                    if($more.hasClass('visible')) return false;
                        $more.animate({marginLeft: 250}).addClass('visible');
                        $more.css('margin-left', 255 + 'px');
                        $(this).addClass('current')
                })
        }).mouseleave(function() {
            if($more.hasClass('visible')) {
                $more.animate({marginLeft: -280}, function(){$more.removeClass('visible')});
                $('#side-nav').find('nav li.more').removeClass('current')
            }
            if($sideNav.hasClass('visible')) {
                $sideNav.animate({marginLeft: -280}, function(){$sideNav.removeClass('visible')});
                if($more.hasClass('visible')) $more.animate({marginLeft: -280}, function(){$more.removeClass('visible')})
            }
        });
        $sideNav.find('nav li:not(.more)').mouseenter(function() {
            if($more.hasClass('visible')) {
                //$more.animate({marginLeft: -280}, function(){$more.removeClass('visible')})
                $('#side-nav').find('nav li.more').removeClass('current')
            }
        });
        $('div#more-categories li.entry').click(function() {
            if ($(this).hasClass('is-adult')){
                {% if not request.user.is_authenticated %}
                    $('div#lightbox .dialog').hide();
                    $('div#lightbox .dialog.login-required-for-adult').show();
                    $('#lightbox').fadeIn();
                    return false;
                {% elif  request.user.is_authenticated and not request.user.adult_authorized %}
                    $('div#lightbox .dialog').hide();
                    $('div#lightbox .dialog.confirm-adult').show();
                    $('#lightbox').fadeIn();
                    return false;
                {% elif request.user.is_authenticated and request.user.adult_authorized %}
                    $(this).find('a').click();
                {% endif %}
            } else {
                $(this).find('a').click()
            }
        });

        $('div#lightbox .dialog.confirm-adult button.confirm').click(function() {
            $('body, button').css('cursor', 'wait');
            $.getJSON("{% url 'me:authorize_adult' %}", null, function(data) {
                $('body, button').css('cursor', 'default');
                if (data.error) alert(data.error);
                else {
                    {% if last_vod_prepayment.adult_authorized %}
                        window.location = "{% url 'movies:home' %}#adult_autorized";
                    {% else %}
                        window.location = "{% url 'movies:bundles' %}";
                    {% endif %}
                }
            })
        })

    })()
</script>

movies/templates/movies/snippets/media_detail_actions.html
{% load i18n %}
{% if IS_VOD_OPERATOR %}
    <div class='poster' style="background-image: url({{ media.poster.small_url }})">
        {% if media.season %}
            <a href="{% url 'movies:series_detail' media.slug %}" class="view-details"></a>
        {% else %}
            <a href="{% url 'movies:movie_detail' media.slug %}" class="view-details"></a>
        {% endif %}
        <div class="actions">
            {% if not request.user.is_authenticated %}
                <a class='play connect' title="{% trans "Watch streaming" %}"></a>
            {% else %}
                <a class='play' title="{% trans "Watch streaming" %}" data-type="media" data-id="{{ media.id }}"></a>
            {% endif %}
{#            {% if media.trailer_slug %}#}
                <button class='trailer' title="{% trans "Watch trailer" %}" data-type="trailer" data-id="{{ media.id }}" style="float: left"></button>
{#            {% endif %}#}
        </div>
    </div>
    <div class='title has-faded-edge'>{{ media.title }}{% if media.season %} {% trans "season" %} {{ media.season }}{% endif %}</div>
    <div class="clicks"> <span>{{ media.display_clicks }}</span> {% trans "views" %}</div>
    <div class="load">{{ media.display_load }}</div>
{% else %}  {# Case of Content Vendor #}
    {% if media.season %}
        <a href="{% url 'movies:series_detail' media.slug %}" class='poster' style="background-image: url({{ media.poster.small_url }})"></a>
    {% else %}
        <a href="{% url 'movies:movie_detail' media.slug %}" class='poster' style="background-image: url({{ media.poster.small_url }})"></a>
    {% endif %}
    <div class='title has-faded-edge'>{{ media.title }}{% if media.season %} {% trans "season" %} {{ media.season }}{% endif %}</div>
    {% if config.vod %}
        <div class="clicks"> <span>{{ media.display_clicks }}</span> {% trans "views" %}</div>
{#        <div class="clicks"> <span>{{ media.display_clicks }}</span> <span class="icon"></span></div>#}
        <span class="load" style="margin-top: 8px">{{ media.display_load }}</span>
        <div class="actions">
            {% if media.trailer_slug %}
                <button class='icon trailer' title="{% trans "Watch trailer" %}" data-type="trailer" data-id="{{ media.id }}" style="float: left"></button>
            {% endif %}
            {% if not request.user.is_authenticated %}
                <button class='icon play connect' title="{% trans "Watch streaming" %}"></button>
                <button class='icon cart connect' title="{% trans "Order for your VOD store." %}"></button>
            {% else %}
                <button class='icon play' title="{% trans "Watch streaming" %}" data-type="media" data-id="{{ media.id }}" style="float: left"></button>
                {% if request.user.has_pending_order %}
                    <button class='icon cart processing' title="{% trans "Order for your VOD store." %}" style="float: left"></button>
                {% else %}
                    <button class='icon cart order confirm' title="{% trans "Order for your VOD store." %}" id="{{ media.id }}"
                            data-title="{{ media.title }}" data-id="{{ media.id }}" data-category='{{ media.category }}' data-load='{{ media.load }}'
                            data-poster="url('{{ media.poster.small_url }}')"  data-is_adult="{{ media.is_adult }}" data-type="media"></button>
                {% endif %}
            {% endif %}
        </div>
    {% else %}
        <div class="orders"> <span>{{ media.display_orders }}</span> <span class="icon"></span></div>
        <span class="load" style="margin-top: 8px">{{ media.display_load }}</span>
        {% if not request.user.is_authenticated %}
            <button class='connect confirm' title="{% trans "Order for your VOD store." %}">{% trans "Order" %}</button>
        {% else %}
            {% if request.user.has_pending_update %}
                <button class='processing confirm' title="{% trans "Order for your VOD store." %}">{% trans "Order" %}</button>
            {% else %}
                <button class='order confirm' title="{% trans "Order for your VOD store." %}" id="{{ media.id }}"
                        data-title="{{ media.title }}" data-id="{{ media.id }}" data-category='{{ media.category }}' data-load='{{ media.load }}'
                        data-poster="url('{{ media.poster.small_url }}')"  data-is_adult="{{ media.is_adult }}" data-type="media">{% trans "Order" %}</button>
            {% endif %}
        {% endif %}
    {% endif %}
{% endif %}

movies/templates/movies/snippets/stream_error.html
{% load i18n %}
{% load staticfiles %}
<div class="stream-error" style="text-align: center">
    <img src="{% static 'img/embarassed-smiley.jpg' %}"/>
    <p></p>
</div>

movies/templates/movies/snippets/user_menu.html
{% load i18n %}
<div id="user-menu" class="icon-menu">
    <div class="icon" style="background-position: -194px -48px; margin-top: 3px"></div>
    <nav class="panel hidden">
        <ul class="has-shade">
            <div class="icon box-arrow"></div>
            <div> <span style="color: #444; font-size: 15px; font-weight: bold; padding: 5px"> {{ request.user.first_name }} </span> </div>
            <li><a href="{% url 'movies:home' %}"> {% trans "Library" %} </a> </li>
            <li><a href="{% url 'me:history' %}"> {% trans "History" %} </a> </li>
            <li><a href="{% url 'me:account_setup' %}"> {% trans "Account info" %} </a> </li>
            <li><a href="{% url 'ikwen:logout' %}?next_url={% url 'movies:home' %}" class="logout"> {% trans "Logout" %} </a> </li>
        </ul>
    </nav>
</div>